name: Build new docker image
on:
  push:
    branches:
      - main
      - fix-githubactions
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      version_changed: 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
           fetch-depth: 2

      - name: Check if version has changed
        id: check_version
        run: |
          git fetch origin main
          git diff --exit-code origin/main -- version || echo "version_changed='true'" >> $GITHUB_ENV

      - name: Set new tag
        if: env.version_changed == 'true'
        run: |
          new_version=$(cat version)
          git tag -v $new_version -m "Version $new_version"
          git push origin $new_version

      - name: Build and push Docker image
        if: env.version_changed == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devcontainer:latest ${{ secrets.DOCKER_USERNAME }}/devcontainer:$(cat version))
          build-args: |
            VERSION=$(cat version)
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
