name: Build new docker image
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      docker_image_name: ${{ vars.DOCKER_USERNAME }}/devcontainer
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
           fetch-depth: 2

      - name: Check if version changed
        id: check_if_version_changed
        run: |
          git diff --exit-code HEAD~1 -- version || echo "result=true" >> $GITHUB_OUTPUT

      - name: Set new tag
        id: set_new_tag
        if: ${{ steps.check_if_version_changed.outputs.result == 'true' }}
        run: |
          new_version=$(cat version)
          git tag $new_version
          git push origin $new_version
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        if: ${{ steps.check_if_version_changed.outputs.result == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        if: ${{ steps.check_if_version_changed.outputs.result == 'true' }}
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: ${{ steps.check_if_version_changed.outputs.result == 'true' }}
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        if: ${{ steps.check_if_version_changed.outputs.result == 'true' }}
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          push: true
          tags: "${{ env.docker_image_name }}:latest,${{ env.docker_image_name }}:${{ steps.set_new_tag.outputs.new_version }}"
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=$(cat version)
